# Generated by Django 5.0.6 on 2024-06-17 04:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Platinum365', 'Platinum'), ('Gold180', 'Gold'), ('Silver90', 'Silver')], max_length=50, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Number must be 12 digits', regex='^\\d{12}$')])),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('assigned_mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Assigned Mobile Number must be 10 digits', regex='^\\d{10}$')])),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('renewal_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.plan')),
            ],
        ),
    ]
